# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170613_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='id',
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='userdata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.UserData'),
        ),
    ]
