# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170613_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswers',
            old_name='userdata',
            new_name='data',
        ),
    ]
