# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170613_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='answer1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='hahaha', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
