# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170614_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_hash', models.CharField(max_length=6)),
            ],
        ),
    ]
