# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashes',
            name='name',
            field=models.CharField(default='registration', max_length=20),
        ),
        migrations.AddField(
            model_name='hashes',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
