# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170614_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='honory_coins',
            field=models.IntegerField(default=20),
        ),
    ]
