# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170615_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogs',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
