# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_transferlogs_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('cost_honory', models.IntegerField(default=0)),
                ('cost_permanent', models.IntegerField(default=0)),
                ('image_src', models.CharField(max_length=255)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserData')),
            ],
        ),
    ]
