# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_marketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitem',
            name='userdata',
        ),
    ]
