# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_marketitem_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='marketitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
