# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20170615_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
