# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20170616_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserData')),
            ],
        ),
    ]
