# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_achievement_image_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassRecQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
