# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20170626_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='social_engineer',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
