# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20170708_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='superuser',
            new_name='is_superuser',
        ),
    ]
