# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20170708_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRedeemer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='hashes',
            name='allowed_hash',
            field=models.CharField(max_length=20),
        ),
    ]
