# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20170709_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashes',
            new_name='Code',
        ),
    ]
