# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20170711_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='achievement',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='social_engineer',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
