# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20170712_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='social_engineer',
            field=models.IntegerField(default=0),
        ),
    ]
