# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20170712_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='driplets_score',
            field=models.IntegerField(default=0),
        ),
    ]
