# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_userdata_driplets_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='items_bought',
            field=models.IntegerField(default=0),
        ),
    ]
