# Generated by Django 2.0.3 on 2018-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_userdata_items_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlogs',
            name='receiver',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferlogs',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
