# Generated by Django 2.0.3 on 2018-04-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20180405_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.School'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.School'),
        ),
    ]
