# Generated by Django 2.0.3 on 2018-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20180405_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
