# Generated by Django 2.0.3 on 2018-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20180405_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(default='registration', max_length=70),
        ),
    ]
