# Generated by Django 2.0.3 on 2018-04-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20180405_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='school',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School'),
        ),
    ]
