# Generated by Django 2.0.3 on 2018-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_portalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='market_items',
            field=models.ManyToManyField(blank=True, to='user.MarketItem'),
        ),
    ]
