# Generated by Django 2.0.3 on 2018-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_bugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='reward',
            field=models.IntegerField(default=20),
        ),
    ]
