# Generated by Django 2.0.3 on 2018-04-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_bugs_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='tier',
            field=models.IntegerField(default=10),
        ),
    ]
