# Generated by Django 2.0.3 on 2018-04-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_marketitem_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogs',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School'),
        ),
    ]
