# Generated by Django 2.0.3 on 2018-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_transferlogs_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogs',
            name='hash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
