# Generated by Django 2.0.3 on 2018-04-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20180421_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SECorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SEQuesAnsw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=200)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School')),
            ],
        ),
        migrations.AddField(
            model_name='secorrectanswer',
            name='se_ques_answ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SEQuesAnsw'),
        ),
        migrations.AddField(
            model_name='secorrectanswer',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserData'),
        ),
    ]
