# Generated by Django 2.0.3 on 2018-04-28 16:46

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20180426_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='image_file',
            field=models.FileField(default=0, upload_to=user.models.image_upload_market),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
