# Generated by Django 2.0.3 on 2018-04-29 17:46

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20180428_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='image_file',
            field=models.ImageField(default='no-image.jpg', upload_to=user.models.image_upload_market),
        ),
    ]
