# Generated by Django 2.0.3 on 2018-05-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20180429_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='link',
            field=models.CharField(default='#', max_length=300),
            preserve_default=False,
        ),
    ]
