# Generated by Django 2.0.3 on 2018-05-03 19:03

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_bugs_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='image_src',
        ),
        migrations.AddField(
            model_name='achievement',
            name='image_file',
            field=models.ImageField(default='no-image.jpg', upload_to=user.models.image_upload_activities),
        ),
    ]
