# Generated by Django 2.0.3 on 2018-05-16 21:46

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_auto_20180516_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='image_file',
            field=models.ImageField(default='C:\\Users\\Vitaly\\OneDrive - Tennessee Technological University\\Work and webdev\\django\\cryptocoin\\cryptocoin\\static/user/img/no-image.jpg', upload_to=user.models.image_upload_market),
        ),
    ]
