# Generated by Django 2.0.3 on 2018-05-16 21:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_auto_20180516_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='image_file',
            field=models.ImageField(default='no-image.jpg', upload_to=user.models.image_upload_market),
        ),
    ]
