# Generated by Django 2.0.3 on 2018-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_auto_20180516_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitem',
            name='cost_honory',
        ),
        migrations.RemoveField(
            model_name='marketitem',
            name='cost_permanent',
        ),
    ]
