# Generated by Django 2.0.3 on 2018-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_auto_20180718_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='cost_permanent',
            field=models.IntegerField(default=0),
        ),
    ]
