# Generated by Django 2.0.3 on 2018-10-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_marketitem_cost_permanent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='team_number',
            new_name='tier',
        ),
    ]
