# Generated by Django 2.1.2 on 2018-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_marketitem_cost_permanent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='description',
        ),
        migrations.RemoveField(
            model_name='school',
            name='state',
        ),
        migrations.AddField(
            model_name='school',
            name='brand',
            field=models.CharField(default='GenCyberCoin', max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='title',
            field=models.CharField(default='GenCyber | Where security meets opportunity', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
