# Generated by Django 2.1.2 on 2018-10-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_auto_20181001_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='team_number',
            field=models.IntegerField(default=0),
        ),
    ]
