# Generated by Django 2.1.2 on 2019-02-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_auto_20181124_0015'),
        ('user', '0069_userdata_team_number'),
    ]

    operations = [
    ]
