# Generated by Django 2.1.2 on 2019-02-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_merge_20190212_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='link',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='code',
            name='allowed_hash',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(default='registration', max_length=100),
        ),
        migrations.AlterField(
            model_name='coderedeemer',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coderedeemer',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passrecquestions',
            name='question',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='author:vitaly_ford', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
