# Generated by Django 2.1.2 on 2019-02-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_auto_20190212_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlogs',
            name='receiver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transferlogs',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
