# Generated by Django 2.1.2 on 2019-02-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_auto_20190212_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlogs',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
