# Generated by Django 2.1.2 on 2019-02-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20190213_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
