# Generated by Django 2.1.2 on 2019-03-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_auto_20190310_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coderedeemer',
            old_name='code_temp',
            new_name='code',
        ),
    ]
