# Generated by Django 2.1.2 on 2019-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_auto_20190310_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderedeemer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
