# Generated by Django 2.1.2 on 2019-03-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_auto_20190310_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderedeemer',
            name='code',
            field=models.CharField(default='nothing-is-here-cant-touch-this!', max_length=255),
        ),
    ]
