# Generated by Django 2.1.2 on 2019-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0081_auto_20190624_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
