# Generated by Django 2.1.2 on 2020-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0092_auto_20200320_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='prevent_ordering',
            field=models.BooleanField(default=False),
        ),
    ]
