FROM heroku/heroku:18

WORKDIR /code

RUN python -m pip install --upgrade pip
RUN apt-get update
RUN apt-get install curl -y

COPY . /code/

RUN python -m pip install -r /code/requirements.txt
RUN python manage.py collectstatic --noinput

ENV RUNNING_ON_HEROKU=1

RUN useradd -ms /bin/bash coinuser
USER coinuser

CMD /bin/bash run_server_on_heroku.sh
